# FROM quay.io/keycloak/keycloak:latest as builder

# # Enable health and metrics support
# ENV KC_HEALTH_ENABLED=true
# ENV KC_METRICS_ENABLED=true

# # Configure a database vendor
# ENV KC_DB=postgres

# WORKDIR /opt/keycloak
# # for demonstration purposes only, please make sure to use proper certificates in production instead
# RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
# RUN /opt/keycloak/bin/kc.sh build

# FROM quay.io/keycloak/keycloak:latest
# COPY --from=builder /opt/keycloak/ /opt/keycloak/

# # # change these values to point to a running postgres instance
# # ENV KC_DB=postgres
# # ENV KC_DB_URL=jdbc:postgresql://10.2.2.111:5432/keycloak
# # ENV KC_DB_USERNAME=ahdev
# # ENV KC_DB_PASSWORD=icub4ucmi
# # ENV KC_HOSTNAME=10.2.2.111

# ENV KC_DB=${KC_DB}
# ENV KC_DB_URL=${KC_DB_URL}
# ENV KC_DB_USERNAME=${KC_DB_USERNAME}
# ENV KC_DB_PASSWORD=${KC_DB_PASSWORD}
# ENV KC_HOSTNAME=${KC_HOSTNAME}
# ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]





# ##to build
# # docker build . -t mykeycloak


# ##run or docker compose
# # docker run --name mykeycloak -p 8443:8443 \
# #         -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
# #         mykeycloak \
# #         start --optimized